### ISSUE TITLE
ServerConfig TypeInitializationException

### ISSUE THREAD

**Issue by billings7** [webappsuk/CoreLibraries#26]
The ServerConfig type throws a TypeInitializationException. This is due to the static Disabled property, which is initialized with a new instance of the class, passing 0 for maximumConnections, which cases a ArgumentOutOfRangeException to be thrown.

**Comment by thargy** [comment]
Have we checked that having zero maximum connections is handled sensibly by the class?  This might be better achieved using a private constructor, whilst keeping the constraint for the public constructor?

**Comment by billings7** [comment]
Everywhere that uses the property checks that it is > 0 before using it. Private constructor is a possibility, depends if people should be able to make their own disabled configs, wanting to specify a name for eg.

**Comment by thargy** [comment]
OK
