### ISSUE TITLE
Initializer Injector doesn't handle writing assemblies containing methods with parameter types from referenced assemblies.

### ISSUE THREAD

**Issue by josh-green** [webappsuk/CoreLibraries#27]
The build process will fail with error `An unexpected error occurred. Failed to resolve assembly` if a method uses parameter types from a referenced assembly.

The error occurs in the Injector when it attempts to [`assembly.Write(assemblyFile, writeParams);`](https://github.com/webappsuk/CoreLibraries/blob/master/Initializer/Injector.cs#L399). It is not looking in the correct directory for the parameter type's assembly within Mono.Cecil.

**Comment by thargy** [comment]
Couple of items here that need reviewing.  In particular the normalisation of the new search directories parameter, plus a discussion on whether this can be automated rather than relying on a path being supplied by manually modifying the calling project.
