### ISSUE TITLE
Support getting the value of output parameters from SqlPrograms

### ISSUE THREAD

**Issue by billings7** [webappsuk/CoreLibraries#29]
Currently there isn't an easy way of getting the value of an output parameter from a SqlProgram. The only option is calling the `Execute*` overload that takes a `SetParametersDelegate` to manually set all the parameters, and storing the SqlParameter whose output value is required.

**Comment by thargy** [comment]
As Output parameters are only available once the reader is disposed, then this Issue is probably related to #24.

**Comment by billings7** [comment]
Implementation should be complete but needs to be tested.
