### ISSUE TITLE
Build failure duplicate references

### ISSUE THREAD

**Issue by GrimeyCoder** [webappsuk/CoreLibraries#3]
Installing WebApplications.Utilities causes the following error. Image attached.

Environment
.NET version 4.5.2
Visual Studio 2013
Windows 8.1
JetBrains Annotations NuGet installed and used prior to installing Utilities.

Error	27	The type 'JetBrains.Annotations.UsedImplicitlyAttribute' exists in both 'c:\Users\rob.lindley\Documents\RedCastle\packages\WebApplications.Utilities.Initializer.5.2.5721.22647\lib\net452\ILMerge.Build.Task.dll' and 'c:\Users\rob.lindley\Documents\RedCastle\packages\JetBrains.Annotations.9.1.1\lib\net20\JetBrains.Annotations.dll'	C:\Users\rob.lindley\Documents\RedCastle\DynamicSpace.RedCastle.eCommerce.Core\Entities\Customer.cs	7	6	DynamicSpace.RedCastle.eCommerce.Core

![image](https://cloud.githubusercontent.com/assets/2250924/9758967/d0b233fc-56e1-11e5-88bb-480143b74481.png)

**Comment by billings7** [comment]
The references added in [this commit](https://github.com/webappsuk/CoreLibraries/commit/f09dfa9f79465e5862c8b3e18d4b66fc309a42db) are probably adding references and dependencies in the nuget when they shouldn't be. As a temp fix, you should be able to remove the reference to ILMerge.Build.Task from the project(s) the nugets are included in (that assembly shouldn't be included anyway).

**Comment by thargy** [comment]
Considering removing some of the complexity of the Initialiser logic and making Module Inititlisation a part of the Utilities NuGet.

**Comment by thargy** [comment]
I believe these failures are no longer present after rewriting the build system logic, please reopen if subsequent issues are found.
