### ISSUE TITLE
Migrate documentation to DocFx

### ISSUE THREAD

**Issue by josh-green** [webappsuk/CoreLibraries#37]
[DocFx](https://github.com/dotnet/docfx) is an open source documentation generator that is highly customisable and integrates well with existing code bases.

It is proposed that the documentation generation process will be added to the main CoreLibraries repo so that it can be easily built by anyone.

The solutions currently use VSDocMan.

**Comment by thargy** [comment]
The migration is now complete, further work will occur under #41.
