### ISSUE TITLE
Add an Email logger

### ISSUE THREAD

**Issue by billings7** [webappsuk/CoreLibraries#47]
Add a logger for sending log messages to configured email addresses.

**Comment by thargy** [comment]
Nice, quite a good idea to make use of the BufferedAction, and we may want to update the other loggers to use a similar trick?

You need to update the ".config.transform" files to include documentation for setting the logger.  Also, you may wish the default HTML style to be placed in a resource file for easier modification?

**Comment by billings7** [comment]
All logs are already buffered based on an amount of time, and I'm not sure the other loggers gain much from buffering based on a count.

I've left the HTML style in the code for now as it can benefit from ReSharper language injections: 
https://blog.jetbrains.com/dotnet/2016/12/26/language-injections-in-resharper-ultimate-2016-3/
