### ISSUE TITLE
Null sql parameter value being passed as default

### ISSUE THREAD

**Issue by Bruddles** [webappsuk/CoreLibraries#51]
This if block is causing a null valued sql parameter to be passed to SQL as default.
When this parameter doesn't have a default, it throws a the exception:

>The parameterized query '(@param decimal(5,2))select @param' expects the parameter '@param', which was not supplied.

https://github.com/webappsuk/CoreLibraries/blob/c1728853a09f5f62a0a5da3730dfa26e0f705873/Database/Schema/SqlProgramParameter.cs#L160-L164

**Comment by billings7** [comment]
Note: This has been fixed as part of the changes made for #45 and related issues, but that branch is not stable yet and contains a number of breaking changes.
